# Generated by Django 2.2.6 on 2019-11-19 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='preferred_genre',
            new_name='genre',
        ),
    ]
