# Generated by Django 2.2.6 on 2019-11-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191119_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='genre',
            field=models.CharField(choices=[('KnvZfZ7vAvd', 'Blues'), ('KnvZfZ7vAeJ', 'Classical'), ('KnvZfZ7vAv6', 'Country'), ('KnvZfZ7vAv1', 'Hip-Hop / Rap'), ('KnvZfZ7vAvE', 'Jazz'), ('KnvZfZ7vAev', 'Pop'), ('KnvZfZ7vAee', 'R&B'), ('KnvZfZ7vAeA', 'Rock')], default='', max_length=25),
        ),
    ]
