# Generated by Django 2.2.6 on 2019-11-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_spotify_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='spotify_username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
