# Generated by Django 2.2.6 on 2019-11-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191121_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='genre',
            field=models.CharField(blank=True, choices=[('KnvZfZ7vAvd', 'Blues'), ('KnvZfZ7vAeJ', 'Classical'), ('KnvZfZ7vAv6', 'Country'), ('KnvZfZ7vAv1', 'Hip-Hop / Rap'), ('KnvZfZ7vAvE', 'Jazz'), ('KnvZfZ7vAev', 'Pop'), ('KnvZfZ7vAee', 'R&B'), ('KnvZfZ7vAeA', 'Rock')], default='', max_length=25),
        ),
    ]
